name: Email Preview Staging Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_EMAIL_PREVIEW_PROJECT_ID }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
on:
  push:
    branches:
      - develop
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            email-preview:
              - 'apps/email/**'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.7.1
      - if: steps.changes.outputs.email-preview == 'true'
        name: 🔧 Install dependencies
        run: pnpm i
      - if: steps.changes.outputs.email-preview == 'true'
        name: 📤 Pull Vercel Environment Information
        run: pnpm dlx vercel env pull .env --yes --environment=staging --token=${{ secrets.VERCEL_TOKEN }}
      - if: steps.changes.outputs.email-preview == 'true'
        name: 📤 Pull Vercel Environment Information
        run: pnpm dlx vercel pull --yes --environment=staging --token=${{ secrets.VERCEL_TOKEN }}
      - if: steps.changes.outputs.email-preview == 'true'
        name: 🏗 Build Project Artifacts
        run: pnpm dlx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - if: steps.changes.outputs.email-preview == 'true'
        name: Deploy Project Artifacts to Vercel
        run: pnpm dlx vercel deploy --target=staging --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}